spring:
  redis:
#    host: localhost
    host: 192.168.88.129
    port: 6379
    password: 123456
    client-type: jedis
    lettuce:
      pool:
        max-active: 16
    jedis:
      pool:
        max-active: 16

