server:
  port: 8080

# debug: true     # 可以开启 debug日志


# 设置日志级别，root代表根节点，即整体应用日志级别
logging:
  # 设置分组
  group:
    ebank: com.jchhh.controller,com.jchhh.service,com.jchhh.dao
    iservice: com.alibaba
  level:
    root: info
    # 设置某个包的日志级别
    com.jchhh.controller: info
    # 设置分组，对某个组设置日志级别
    ebank: info
    iservice: warn

  # 设置日志的模板格式
#  pattern:
#    console: "%d - %m %n"
#    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
