spring:
  task:
    scheduling:
      pool:
        size: 1   # 线程池大小，默认为 1
      thread-name-prefix: spring_task_
      shutdown:
        # 线程池关闭时等待所有任务完成
        await-termination: false
        # 调度线程关闭前最大等待时间，确保最后一定关闭
        await-termination-period: 10s