server:
  port: 8083


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot_db?serverTimezone=UTC
      username: root
      password: 123456
  boot:
    admin:
      client:
        url: http://localhost:8080


mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

info:
  appName: @project.artifactId@
  version: @project.version@
  company: 可乐鸡翅
  author: jchhh
